### ISSUE TITLE
enhancement - improve consistency of wording for lagging / latency / delay concepts

### ISSUE THREAD

**Issue by sebwurl** [trackme-limited/trackme-report-issues#10]
Sometimes I'm a bit confused about the wording in context of lags. I have to think twice what I'm looking at or what belongs together. Maybe there is room for improvement.

Metrics and thresholds are called _ingest lag_, _latency_  and _lag max_, although the belong to the same concept.
On the other side there are _event lag_ and _delay max_ which belong to the same concept.

Additionally the KPI in the "Overview data source" tab is named "avg_lag_sec". It is not clear, that this is about the _ingest lag_ / _latency_

**Comment by guilhemmarchand** [comment]
A first level of changes and wording fixes has been implemented with v2.0.12
More to come in the future releases to make things more consistents.

**Comment by guilhemmarchand** [comment]
Considered to be handled properly now.
