### ISSUE TITLE
enhancement - Data Source/Host (splk-dsm/dhm) - Allows managing data in the future detection on a per entity basis

### ISSUE THREAD

**Issue by sebwurl** [trackme-limited/trackme-report-issues#101]
In my case a very very small percentage (0.001%) of events show up with future events and constantly lead to status flipping/alarming. Of course the root-cause should be fixed, nevertheless it would be nice to have a disabling option for the future event detection per entity or the option to define a custom threshold per entity.

**Comment by guilhemmarchand** [comment]
@sebwurl 

FYI, TrackMe provides a builtin option for you to control the tolerance of events in the future:

<img width="1773" alt="image" src="https://user-images.githubusercontent.com/7503059/234124384-e5ed68b4-138b-44e7-864e-4b5804eaba12.png">

One option for you would be to increase the tolerance value according to your context, it defaults to 10 minutes.

Regarding the option to disable the future detection on a per entity, understood, will be considered.

**Comment by sebwurl** [comment]
Hi,
I'm aware of this global setting, but it may not be optimal in some scenarios to increase it as this will effect all entities. Thanks for considering such an option.

**Comment by guilhemmarchand** [comment]
Hi @sebwurl !
Yes - totally we will, we've been focussing a lot on a new component recently but yes we will consider it very soon

**Comment by guilhemmarchand** [comment]
@sebwurl 

Will be available in upcoming 2.0.34:

<img width="1766" alt="image" src="https://github.com/trackme-limited/trackme-report-issues/assets/7503059/6281d7ea-4a0c-49b3-ad96-1576a0d6b4d1">

- You can the value to "system" which means you rely on the system level
- You can a custom negative value to override the default system value
- You can set to disabled, which does not fully disable this as it has to be a negative numerical value, but sets to -7d allowing data in the future up to 7days without affecting the entity state

Version 2.0.34 will be published shortly
