### ISSUE TITLE
bug - all components - Tracking Alerts UI always created splk-dsm Alert

### ISSUE THREAD

**Issue by Stjubit** [trackme-limited/trackme-report-issues#110]
**Describe the bug**

The **Tracking Alerts UI** always creates `splk-dsm` alerts, even if you select `splk-dhm` or `splk-mhm` as a type.

The search always references the `get_splk_dsm_table`. However, it should reference `get_splk_dhm_table` for splk-dhm and `get_splk_mhm_table` for splk-mhm alerts.

**TrackMe version**

`2.0.29`

**To Reproduce**

1. Open a virtual tenant
2. Switch to the `Tracking Alerts` tab
3. Create a new alert of type `splk-dhm` or `splk-mhm`
4. Check the resulting search in `savedsearches.conf`

**Expected behavior**

The searches reference the correct macro.

**Splunk version and deployment:**

**Splunk:** `9.0.4`
TrackMe is deployed on a dedicated SH.

**Additional context**

I guess `tk_input_create_alert_splk_dsm` is always true and this is the bug.

**Comment by guilhemmarchand** [comment]
You are entirely right @Stjubit thank you a thousands time for raising it - will be fixed shortly!

**Comment by guilhemmarchand** [comment]
FIxed in release 2.0.30 published in Splunk Base

**Comment by Stjubit** [comment]
Thanks ❤️
