### ISSUE TITLE
enhancement: Higher width for the status column (which can truncated under Ack circumstances)

### ISSUE THREAD

**Issue by sebwurl** [trackme-limited/trackme-report-issues#145]
In the feeds overview tables, the status indicator is hidden in case of an acknowledgement. It would be great to have a higher column width to show both, without having to change the width manually every time the table is opened.

![image](https://github.com/trackme-limited/trackme-report-issues/assets/85566586/0afe5a49-3d46-4c6c-a412-30cf2c0fa0f5)

**Comment by guilhemmarchand** [comment]
Thank you @sebwurl will be reviewed.

FYI, in version 2.0.36, a new concept has been implented with Tenants account, which allow more flexibility to configure per tenant preferences.

Between the preferences, you can influence the minimal width of the object column.

Therefore, one option could be to allow more columns to be modified through the same principle.

**Comment by guilhemmarchand** [comment]
Fixed in release 2.0.37 @sebwurl
