### ISSUE TITLE
TrackMe bug report - DHM delay and lag values are reset to defaults

### ISSUE THREAD

**Issue by sebwurl** [trackme-limited/trackme-report-issues#146]
On v.2.0.33 I'm experiencing that the DHM delay and lag values are reset to the defaults by the hybrid tracker.

We had a similar issue here #44. This time the macro definitions are correct, but it still behaves in such a way.

Steps to reproduce:
- Change DHM lag & delay thresholds in the overview table or by using the "modify" interface
- Refresh the table, the thresholds look correct
- Run the Hybrid tracker manually
- Refresh the DHM table > the thresholds are reset to the configured default values

**Comment by guilhemmarchand** [comment]
@sebwurl 
I believe all splk-dhm related issues have been addressed in 2.0.36, the vetting processing is currently pending and I think should happen very shortly.

Can we please keep this one, and review again on your side once you have upgraded to 2.0.36.

**Comment by sebwurl** [comment]
Ok, I will review it in v2.0.36 and let you know.

**Comment by guilhemmarchand** [comment]
@sebwurl 
A remaining logic issue was identified and fixed in 2.0.38.

Thank you!
