### ISSUE TITLE
bug/enhancement - Single forms and Donut drilldown do not lead to actions (all components)

### ISSUE THREAD

**Issue by sebwurl** [trackme-limited/trackme-report-issues#16]
I guess the 4 single values in the tracking overview dashboards should change the filters of the table below as in TrackMe v1. This was very comfortable to navigate to the alerted entities. In v2.0.4 the drilldowns are not working.

**Comment by guilhemmarchand** [comment]
Thank you @sebwurl 
Fair enough - will be addressed in next release train.

**Comment by guilhemmarchand** [comment]
work is in progress - was redirected for 2.0.9 milestone.
