### ISSUE TITLE
TrackMe bug report - Data sampling state "pending"

### ISSUE THREAD

**Issue by sebwurl** [trackme-limited/trackme-report-issues#17]
Using the "Clear stats & run sampling" function results in a never ending pending status for the affected data source.

![image](https://user-images.githubusercontent.com/85566586/220073396-919a3d04-0f39-4724-aa4c-c7327109bbc4.png)

Is there a workaround to fix this issue manually per data source?

**Comment by guilhemmarchand** [comment]
@sebwurl 

Can you run the following SPL command please:

- update the tenant_id and object accordingly

```
| trackme mode=post url="/services/trackme/v2/splk_dsm/ds_manage_data_sampling" body="{'tenant_id': 'local-feeds', 'object_list': 'firewall:pan:traffic|key:region|acme-emea', 'action': 'run'}"
```

**You expect an answer like:**

<img width="1518" alt="image" src="https://user-images.githubusercontent.com/7503059/220086084-262bb690-e40f-49b5-9af9-e2ca70c4c36f.png">

**Here is the workflow:**

**Run sampling**

```
| trackme mode=post url="/services/trackme/v2/splk_dsm/ds_get_dsm_sampling" body="{'tenant_id': 'local-feeds', 'object': 'firewall:pan:traffic|key:region|acme-emea', 'action': 'run'}"
```

Traces:

```
index=_internal sourcetype=trackme:rest_api post_ds_manage_data_sampling
```

**Clear state and run Sampling**

--> reset:

```
| trackme mode=post url="/services/trackme/v2/splk_dsm/ds_manage_data_sampling" body="{'tenant_id': 'local-feeds', 'object_list': 'firewall:pan:traffic|key:region|acme-emea', 'action': 'reset'}"
```

**Expected trace in:**

```
index=_internal sourcetype=trackme:rest_api post_ds_manage_data_sampling
```

```
2023-02-20 10:42:01,765 INFO trackme_rest_handler_splk_dsm.py post_ds_manage_data_sampling 2598 tenant_id="local-feeds", object="firewall:pan:traffic|key:region|acme-emea", action="reset", KVstore record was successfully deleted
```

--> run:

```
| trackme mode=post url="/services/trackme/v2/splk_dsm/ds_get_dsm_sampling" body="{'tenant_id': 'local-feeds', 'object': 'firewall:pan:traffic|key:region|acme-emea', 'action': 'run'}"
```

traces from the executor:

```
index=_internal sourcetype=trackme:custom_commands:trackmesamplingexecutor tenant_id="local-feeds"
```

ex:

```
2023-02-20 10:42:35,850 INFO trackmesamplingexecutor.py generate 312 tenant_id="local-feeds" Executing data sampling resulting search="search index="firewall" sourcetype="pan:traffic" region="acme-emea" | head 100
| eval key="c6fd2957cbcad1650d5bbee8b751bfa4", object="firewall:pan:traffic|key:region|acme-emea"
| rename _raw as raw_sample, sourcetype as data_sourcetype"
```

Not all traces will be related to the object, such as:

```
2023-02-20 10:48:42,957 INFO trackmesamplingexecutor.py generate 360 tenant_id="local-feeds" data sampling job successfully executed, status="success", run_time="36.307127237319946", report_name="trackme_dsm_data_sampling_tracker_tenant_local-feeds", entities_count="1"
```

**Comment by sebwurl** [comment]
The reset works according to the output:
![image](https://user-images.githubusercontent.com/85566586/220106114-4234518a-ae6b-4272-b44b-5a6ff86ea344.png)

But there is no trace like expected:

![image](https://user-images.githubusercontent.com/85566586/220106308-30f14c9f-bdf1-454a-8050-3f419ca08274.png)

The next run results in a pending status again. Again the expected trace is missing:

![image](https://user-images.githubusercontent.com/85566586/220106592-8baca6ba-a2e4-4a03-ab8c-3e332c2cc4e5.png)

![image](https://user-images.githubusercontent.com/85566586/220106924-3399a564-4b97-40a4-ae65-4e7c6e1654a6.png)

**Comment by guilhemmarchand** [comment]
@sebwurl 

Sorry, to request a manual run it's

```
| trackme mode=post url="/services/trackme/v2/splk_dsm/ds_manage_data_sampling" body="{'tenant_id': 'local-feeds', 'object': 'firewall:pan:traffic|key:region|acme-emea', 'action': 'run'}"
```

This renders the status:

```
| trackme mode=post url="/services/trackme/v2/splk_dsm/ds_manage_data_sampling" body="{'tenant_id': 'local-feeds', 'object': 'firewall:pan:traffic|key:region|acme-emea'}"
```

Regarding the traces, you should see many various traces, if you do not then you do not have access to the _internal index which is where these events end up.

What likely could be happenning, the run will show the result and its results, would be that there won't be any data retrieved by the search.

The Sampling executor has an hard coded earliest to the past 24hours. (not hard coded in fact, it's an argument of the search)

Depending on your run, we will see what the reason would be.

We could extend the feature to allow for an optional earliest / latest to be set, also I will verify why it didn't return the hand when you raised the run through the UI

**Comment by sebwurl** [comment]
I recognized a scheduler error in the _internal index.
It says that the report trackme_dsm_data_sampling_tracker_tenant_<mytenant> has an error in the eval command. By analyzing this search it turned out, that the macro trackme_data_sampling_engine was not working. I deleted custom sampling rules and now it seems to work. Maybe a bad configured regex caused a syntax error in the SPL.

**Comment by guilhemmarchand** [comment]
Interesting.
I will try to reproduce

Did you see anything in

```
index=_internal sourcetype=trackme:custom_commands:trackmesamplingexecutor log_level=error
```

**Comment by sebwurl** [comment]
So far I haven't been able to reproduce it.
There are success logs in _index=_internal sourcetype=trackme:custom_commands:trackmesamplingexecutor_ until I broke the macro. Then no events are logged for this sourcetype until I deleted my custom sampling rules and success messages started to come in again.
The errors I found are logged in index=_internal sourcetype=scheduler.

**Comment by guilhemmarchand** [comment]
Thank you @sebwurl 

I believe I can reproduce and understand the issue.
As well, from the UI perspective likely, Javascript didn't notice that the search failed at the lowest bootstrap level - something we can address.

Will update you here.

**Comment by sebwurl** [comment]
Now was able to reproduce the behaviour (but not the exact same error message).
Create a custom sampling rule with a single unescaped parantheses as regex. This results in an invalid SPL for _trackme_dsm_data_sampling_tracker_tenand_mytenant_. Again this is logged in sourcetype=scheduler, but not in sourcetype=trackme:custom_commands:trackmesamplingexecutor log_level=error.

**Comment by guilhemmarchand** [comment]
@sebwurl 
This being reviewed, planning to have a more Pythonic approach with individual thread managing the sampling logic, such that a malformed regex will not impact globally the sampling feature.

**Comment by guilhemmarchand** [comment]
Better late than never @sebwurl !

TrackMe 2.1.0 will welcome the data sampling engine v2, a totally rewritten concept for sampling in TrackMe, fully written in Python and way more robust, flexible and powerful than the current implementation.

Betweem many other things, this also makes this issue impossible to happen.

**Comment by sebwurl** [comment]
I recognized a lot of entities (all discovered since the update to 2.1.0) that have a sampling state "pending":
![image](https://github.com/user-attachments/assets/dec35ee8-94d2-49b3-81ec-06db4d154205)

Running "run sampling now" for these entities solves this immediately. Nevertheless, I'm sure the engine should take care of this.
I've not found any logs about the sampling engine that include my object names.

**Comment by guilhemmarchand** [comment]
Hi @sebwurl 

Does the job execute correctly?
https://docs.trackme-solutions.com/latest/admin_guide_data_sampling.html#troubleshooting

Also in here:
https://docs.trackme-solutions.com/latest/admin_guide_data_sampling.html#high-level-overview-of-the-data-sampling-process

The job starts with an inputlookup search which is traced in the logs:

```
index=_internal sourcetype=trackme:custom_commands:trackmesamplingexecutor "Executing upstream definition search"
```

entities pending should be part of that - Will also review!

**Comment by guilhemmarchand** [comment]
Ok I think I see what we can happen.

If you look at the "upstream search", would be something like:

index=_internal sourcetype=trackme:custom_commands:trackmesamplingexecutor "Executing upstream definition search"

example:

```
| inputlookup trackme_dsm_tenant_feeds-tracking where monitored_state="enabled"
| eval key=_key
| `trackme_exclude_badentities`
| where data_last_time_seen>relative_time(now(), "-24h")
| lookup trackme_dsm_data_sampling_tenant_feeds-tracking object OUTPUT data_sample_feature, relative_time_window_seconds, data_sample_last_entity_epoch_processed, min_time_btw_iterations_seconds, data_sample_mtime
``` only consider entities where the last processed epoch (data_sample_last_entity_epoch_processed) is older than data_last_time_seen, or null (entities has not been processed yet) ```
| where (isnull(data_sample_last_entity_epoch_processed) OR data_sample_last_entity_epoch_processed<data_last_time_seen)
| eval data_sample_feature=if(isnull(data_sample_feature), "enabled", data_sample_feature) | where (data_sample_feature!="disabled")
``` only consider entities where the min_time_btw_iterations_seconds is older than the current time (bigger or equal to the time spent since last run, or null for new entities) ```
| eval time_spent_since_last_run=now()-data_sample_mtime
| where (isnull(min_time_btw_iterations_seconds) OR time_spent_since_last_run>=min_time_btw_iterations_seconds)
``` define a priority rank, entities that have been set as disabled_auto should be processed last compared to entities in disabled_audo ```
| eval priority_rank=if(data_sample_feature=="enabled", 1, 2)
``` order ```
| sort limit=0 priority_rank, data_sample_mtime
| fields object, key, data_last_time_seen, *
| eval earliest_target=if(isnum(relative_time_window_seconds), data_last_time_seen-relative_time_window_seconds, data_last_time_seen-3600)
```

The Python underneath then uses the earliest_target, so we it defines it as relative to the latest events received, for some reasons we end up with an invalid earliest / latest.

Also, the failure should not impact the next entities, but there might be something unexpected - reviewing - will open a brand new issue.

**Comment by sebwurl** [comment]
I will disable the object causing the error. Maybe that helps all the rest and narrow down the problem.

**Comment by sebwurl** [comment]
BTW: This entity has future events, so latest events events will most likely cause this issue.

**Comment by guilhemmarchand** [comment]
Ohhhhhh!!! 

Damned - that makes sense - so strange we missed this @sebwurl thanks - I'll open an issue and it will be 2.1.2!

**Comment by guilhemmarchand** [comment]
@sebwurl 
FYI: https://github.com/trackme-limited/trackme-report-issues/issues/786
