### ISSUE TITLE
bug - User Interface - Using DSM "Show disabled entities" filter clears the "Filter field or function" dropdown

### ISSUE THREAD

**Issue by sebwurl** [trackme-limited/trackme-report-issues#176]
Hi,

I'm on v.2.0.37. When using the "Show disabled entities" filter in the DSM overview table, it clears the "Filter field or function" dropdown and removes all filters from the table. To use filters, users have to reset "Filter field or function" manually.
![image](https://github.com/trackme-limited/trackme-report-issues/assets/85566586/2b70ee7a-b369-4b67-bb8f-9be1f91aff9a)

**Comment by guilhemmarchand** [comment]
Thank you for reporting @sebwurl - totally right you are.
