### ISSUE TITLE
bug - Data Sources (splk-dsm) - Clear state & run sampling resets the entity for DSM

### ISSUE THREAD

**Issue by sebwurl** [trackme-limited/trackme-report-issues#192]
Hi,

on v2.0.38 I'm experiencing that the option "Clear state & run sampling" option removes the entity from the DSM overview and the entity is "discovered" again with the next tracker schedule. This new discovery also resets configurations like the priority and thresholds.
I can reproduce it by using Clear state & run sampling multiple times. The status flipping tab shows the discovery:
![image](https://github.com/trackme-limited/trackme-report-issues/assets/85566586/243db218-9222-45fb-96ec-041172e422c4)

**Comment by guilhemmarchand** [comment]
Thanks @sebwurl for raising it - agreed on the issue
