### ISSUE TITLE
Feature request - Increase character limit for data sampling

### ISSUE THREAD

**Issue by sebwurl** [trackme-limited/trackme-report-issues#250]
Data sampling creates false positives from time to time. I have a rule like this **^{.*}$**
and the sampling engine seems to truncate sample events to 50k characters. So the entity is alerted although the raw event is complete.

It might be an edge case, but maybe there is an easy solution for it.
I'm on version 2.0.47.

**Comment by guilhemmarchand** [comment]
@sebwurl 

In TrackMe 2.1.0, events are now parsed without any truncation, therefore regular expressions are parsed against the entire events content.
What TrackMe stores in the KVstore collection are a sample of records per model matched (which number is configuration globally or per entity)
