### ISSUE TITLE
bug - Entity remains in red state due to Data sampling detection altrhough the feature has been disabled

### ISSUE THREAD

**Issue by sebwurl** [trackme-limited/trackme-report-issues#28]
Hi,
an Entity flipped to red because multiformat was detected by the sampling engine. Sampling is disabled but the entity remains in a red state. I cleared the state and it happens again. Am I missing something here?

**Comment by sebwurl** [comment]
After a while it flipped to green.

**Comment by sebwurl** [comment]
I'm experiencing this again. In a prod environment v2.0.7 and I can reproduce it in my lab v2.0.10 as well.
A data source flipped to red and was acknowledged due to a detected multiformat.
I disabled the data sampling, but it is still red/acknowledged for a while. The performed action in the audit events look like this:

![image](https://user-images.githubusercontent.com/85566586/222443953-3f856cd3-7453-4918-8650-7ca7f32bc446.png)

**Comment by guilhemmarchand** [comment]
Investigating @sebwurl

**Comment by guilhemmarchand** [comment]
Fixed in 2.0.11 @sebwurl
