### ISSUE TITLE
Bulk Edit disable action to allow/request for comment on the change

### ISSUE THREAD

**Issue by TiagoTLD1** [trackme-limited/trackme-report-issues#302]
**Is your feature request related to a problem? Please describe.**
In dsm, selecting multiple entities and trying to Bulk Edit Selected opens the menu where we can "disable" monitoring. This does not request for a comment, as opposed to the individual entity disable. I faced the need to disable 130 entities in a row and it would be good to be able to jot down a note.

**Describe the solution you'd like**
Replicate the comment that exists for individual changes into the bulk edit.

**Describe alternatives you've considered**
Not putting any notes. The alternative would be to go through each entity and disable and note. Unfeasible

**Comment by TiagoTLD1** [comment]
Missed the "COnfirm Bulk Update". Please ignore this

**Comment by guilhemmarchand** [comment]
Not a problem at all @TiagoTLD1 !
