### ISSUE TITLE
TrackMe bug report - Hybrid Tracker cron no applied in the report schedule

### ISSUE THREAD

**Issue by TiagoTLD1** [trackme-limited/trackme-report-issues#303]
**Describe the bug**
When creating a new Hybrid tracker in DSM, the cron schedule input is not reflected in the alert cron. This can be checked by the immediately generated JSON where the cron remains "randomly every 5m", and also in Searches Reports and Alerts table.

**TrackMe version**
2.0.60

**To Reproduce**
Create a new hybrid tracker in DSM, set a cron different from */5 * * * * and note that the it does not apply for the subsequent runs

**Expected behavior**
Cron input to be applied in the tracker schedule

**Screenshots**

![tracker_cron](https://github.com/trackme-limited/trackme-report-issues/assets/22215503/87a6c235-84c8-4e58-a224-38806b368a2b)
![tracker_json](https://github.com/trackme-limited/trackme-report-issues/assets/22215503/d2e70e8d-cd02-45be-a0f2-161f42d87ea3)

**Splunk version and deployment:**

9.1.1
Search Head Cluster (SHC)

**Comment by guilhemmarchand** [comment]
Thank you @TiagoTLD1 - Will be reviewed shortly!
