### ISSUE TITLE
enhancement - Improve custom break by explanation and automatically remove default fields if entered unexpectly by the user

### ISSUE THREAD

**Issue by sebwurl** [trackme-limited/trackme-report-issues#32]
The **Custom breakby field** option does not work as expected.
I tried to split by index,sourcetype,env but the test function shows an error. In this case _env_ is an indexed field:

![image](https://user-images.githubusercontent.com/85566586/222384183-9489140c-b390-4412-9625-00d14f495abb.png)
![image](https://user-images.githubusercontent.com/85566586/222385123-41759651-1db9-4b55-9779-08d7e97a532c.png)
Reasons seems to be the repeated group-by fields.

It also happens when I just use a custom split by index and sourcetype (so what is done by default).

**Comment by guilhemmarchand** [comment]
@sebwurl 

It is not a bug, but explanations should be improved and we shall include a safety to remove fields which would be a repeat.

You must NOT repeat the default fields, for instance if you want to break with "region,company" you would set:

<img width="1439" alt="image" src="https://user-images.githubusercontent.com/7503059/222388528-90de1974-eaf4-45e0-a5d4-d2a713253df0.png">

The explanations in the Hybrid wizard are ok however:

<img width="1394" alt="image" src="https://user-images.githubusercontent.com/7503059/222388782-7fc649f3-78fe-4a9c-a201-32c96f7f5bf2.png">

Will keep your issue as an enhancement as it's not a bug.

**Comment by sebwurl** [comment]
Makes totally sense. I was a little hasty. Thanks for the clarification.
