### ISSUE TITLE
TrackMe bug report - No events in index=trackme_notable

### ISSUE THREAD

**Issue by sebwurl** [trackme-limited/trackme-report-issues#371]
Hi,
I recognized missing notable events in index=trackme_notable in v.2.0.65 & 2.0.66 (on-prem). Status flipping is shown for the entity as well as a correct status message, but there are no notable events written. trackme_summary and trackme_audit are filled.
I tried to upgrade to v.2.0.71, but notable events are not showing up. 
I deleted the TrackMe app and started with a fresh install and all defaults, but this did not help either.
I was not able to find any error message in the logs so far.

Do you have any idea what is happening here?

**Comment by sebwurl** [comment]
I think it can be closed as notable events are only created by alert actions. I thought they are created with every status flipping.

**Comment by guilhemmarchand** [comment]
Hi @sebwurl !

Hope you are doing well ;-)

These are indeed, please have a look at the following documentation:
https://docs.trackme-solutions.com/latest/admin_guide_alerts.html

The architecture based on Notables is what we recommend, and you should find the right information out there.

Any more question please reach out!

kind regards,

Guilhem
