### ISSUE TITLE
feature request - Overview Table: Column for human readable thresholds

### ISSUE THREAD

**Issue by sebwurl** [trackme-limited/trackme-report-issues#388]
It would be great to have two additional columns for "human readable" thresholds in the main overview tables.
For example  next to delay=2700 a column with 00:45:00 for a faster understanding of the config. Basically just translating the values with the tostring function.
![image](https://github.com/trackme-limited/trackme-report-issues/assets/85566586/d76d59c5-e644-4adb-947d-d25e0e77dcf1)

This would be a nice help in the entities details page as well (the one that appears when the entity is clicked):
![image](https://github.com/trackme-limited/trackme-report-issues/assets/85566586/53160c00-9f90-4299-9c5c-6b3bce2593b1)

**Comment by guilhemmarchand** [comment]
Ready for TrackMe 2.0.72 @sebwurl 
Thank you
