### ISSUE TITLE
feature - Data Hosts / Metric Hosts tracking - Allows tracking expected entities rather than actively discovered entities (load expected entities from a third party)

### ISSUE THREAD

**Issue by sebwurl** [trackme-limited/trackme-report-issues#39]
Would it be possible to create workflow to add expected entities? Let's say in a rollout, 100 additional UFs will be onboarded to send data. I can perfectly monitor their state , if they sent data once. But I'm not able to identify UFs that never send data for whatever reason, although they should.

Would a feature be conceivable to address this, like creating dummy entries for all expected new hosts? Does that make sense in the scope of TrackMe?

**Comment by guilhemmarchand** [comment]
Will be considered @sebwurl 
Not the very first time a similar feature has been requested.

**Comment by guilhemmarchand** [comment]
Hi @sebwurl !

Better late than never ;-)
It is now possible from 2.0.64, and it has been documented here:

https://docs.trackme-solutions.com/latest/admin_guide_expected_hosts.html

Thank you for your patience
