### ISSUE TITLE
enhancement - Future data detection - Take into account a negative latency as a likely data in the future use case and turn entity orange as expected when future detection is operated against _time

### ISSUE THREAD

**Issue by sebwurl** [trackme-limited/trackme-report-issues#392]
TrackMe v. 2.0.66 OnPrem

I recognized green status values for some entities although the latency shows a negative value:
![image](https://github.com/trackme-limited/trackme-report-issues/assets/85566586/b847f355-98be-48f8-bfe7-a99aac3ed854)

I would expect this to be in a orange state as it indicates future events. In this case the datasource it a bulk ingest once a day, I think that is why the delays turns into a positive value at some point.

**Comment by guilhemmarchand** [comment]
Hi @sebwurl 

Hum! 

Actually, the detection of events in the future is performed against _time, which is traduced in TrackMe by the delay metric.

For splk-dsm, this is in the following macro:

```
[trackme_eval_splk_dsm_state(1)]
```

Then:

```
| eval object_state=if(data_last_lag_seen<future_tolerance, "orange", object_state)\
```

I am a little bit suspiscious on a negative latency should be interpreted here, events in the future should in a mandatory manner be considered via a negative delay, especially TrackMe gets the max(_time) so there's no room for errors here if you like.

This one entity looks very supiscious, in short events in the future should be detected by the _time, not _indextime

**Comment by sebwurl** [comment]
Indeed, it looks suspiscious. The metrics graph is like this:
![image](https://github.com/trackme-limited/trackme-report-issues/assets/85566586/bb2cb0c9-8124-4160-917c-22f90caf9b79)

Here are my thoughts:
It is a bulk ingest and events are indexed with future timestamps. Latency is negativ as well as as the delay. As time goes by the timestamps "move" towards now and at some point they are no longer future timestamps (and no new data was ingested so far). So delay turns into a positive value at that point. On the other hand the latency never changes until new data comes in and remains negative all the time. Analyzing the entity state over time for the entity above show this:
![image](https://github.com/trackme-limited/trackme-report-issues/assets/85566586/027e4e8a-1c22-4c71-9840-0a162c124381)

**Comment by guilhemmarchand** [comment]
Hi @sebwurl 

Do you expect anything further from us regardgin this use case? (I mean anything you think we should better handle in the end?)

Guilhem

**Comment by sebwurl** [comment]
From my point of view a negative ingest lag is an indicator for future events as well and covers the special scenarios mentioned above somewhat more precisely in terms of visibility. I would say it is a "nice to have" when it can be implemented easily, because the current approach covers it at specific points in time and can be altered properly.

**Comment by guilhemmarchand** [comment]
Thank you @sebwurl - looking at this.

**Comment by guilhemmarchand** [comment]
@sebwurl 

From 2.0.77, both a negative delay and/or a negative latency beyond accepted thresholds will be treated as data in the future:

<img width="1725" alt="image" src="https://github.com/trackme-limited/trackme-report-issues/assets/7503059/411302b3-d0ec-4187-9b1c-958fdc7295f9">
