### ISSUE TITLE
feature - Add Ack duration and Ack type as customizable options for bulk edit actions

### ISSUE THREAD

**Issue by sebwurl** [trackme-limited/trackme-report-issues#393]
It would be nice to have the "ack duration" for the bulk edit, like it possible to define per entity. Currently the ack is set for 1d by default with bulk edit.

**Comment by guilhemmarchand** [comment]
Thanks - this makes sense @sebwurl

**Comment by guilhemmarchand** [comment]
<img width="1709" alt="image" src="https://github.com/trackme-limited/trackme-report-issues/assets/7503059/eddcc06f-2dd6-4c78-8ddf-683970e9d0c3">

Thanks for raising @sebwurl - in 2.0.72 ready
