### ISSUE TITLE
Feature Request: Acknowledgement overlay in Tabulator tables (right click context popover)

### ISSUE THREAD

**Issue by sebwurl** [trackme-limited/trackme-report-issues#398]
I would be great to have an overlay for the acknowledgement icon in the main overview to show the defined comment (like the overlay that can be opened with a right click the entity). To have the chance for a quick info without drilling down into the identity ack settings.

**Comment by guilhemmarchand** [comment]
Thank you @sebwurl ready for 2.0.75:

![image](https://github.com/trackme-limited/trackme-report-issues/assets/7503059/6f1b5f52-6c63-4e4f-a016-f0719a8287a7)
