### ISSUE TITLE
bug - Hybrid Trackers / Flex Object trackers - latest_time is not used during tracker creation

### ISSUE THREAD

**Issue by sebwurl** [trackme-limited/trackme-report-issues#451]
In v2.0.81 I created a new hybrid tracker with earliest=-7d latest=+7d. The latest is not used, instead it is configured as latest=+4h (the default value)

![image](https://github.com/trackme-limited/trackme-report-issues/assets/85566586/922d0185-3a96-4b7b-affc-934c7b3dc209)

![image](https://github.com/trackme-limited/trackme-report-issues/assets/85566586/1832ac89-eed3-452b-9a8e-c5ef68803d7d)

**Comment by guilhemmarchand** [comment]
Thanks @sebwurl  as always ;-) 

Good catch, the bug is actually in the API endpoint (for both hybrid tracker and flex objects), the code is currently:

```
                # earliest_time and latest_time for the tracker, if not specified, defaults to -4h / +4h for dsm|dhm and -5m/+5m for mhm
                try:
                    earliest_time = resp_dict["earliest_time"]
                except Exception as e:
                    if component in ("dsm", "dhm"):
                        earliest_time = "-4h"
                    elif component in ("mhm"):
                        earliest_time = "-5m"

                try:
                    latest_time = resp_dict["latest"]
                except Exception as e:
                    if component in ("dsm", "dhm"):
                        latest_time = "+4h"
                    elif component in ("mhm"):
                        latest_time = "+5m"
```

But the latest should have been:

```
latest_time = resp_dict["latest"]
```
