### ISSUE TITLE
bug - Logical Group - object is red even though logical group has sufficient green members

### ISSUE THREAD

**Issue by bdcrandall** [trackme-limited/trackme-report-issues#456]
**Describe the bug**
I couldn't reopen bug #413 but the issue is still present after upgrading past v2.0.75

**TrackMe version**
2.0.76

**To Reproduce**
I have several logical groups.  I deleted and re-created all of them after the upgrade to v2.0.76.  Currently only one group is behaving correctly and turning data sources blue, the rest seem to have no effect at all and turn red based on their individual thresholds.

**Expected behavior**
The data sources in logical groups should turn blue as long as sufficient members remain green.

**Screenshots**
![trackmev2_bug01](https://github.com/trackme-limited/trackme-report-issues/assets/66020496/be88e5f5-93ea-4714-9a14-588a39565d47)
![trackmev2_bug02](https://github.com/trackme-limited/trackme-report-issues/assets/66020496/d963487a-adac-43b1-ab62-0be8381220db)
![trackmev2_bug03](https://github.com/trackme-limited/trackme-report-issues/assets/66020496/06f1fb89-5f38-4fcc-806f-4f6265ded4df)
![trackmev2_bug04](https://github.com/trackme-limited/trackme-report-issues/assets/66020496/c5db1127-79bc-4ad3-9f70-e1f1603c6ef8)

**Splunk version and deployment:**
Splunk Cloud
Version: 9.0.2303.201
Build: 5480631d4591
Experience: Classic
Standalone search head

**Additional context**
Nothing relevant that I can think of.

**Comment by guilhemmarchand** [comment]
Hi @bdcrandall 

Right, we will get the bottom of this.

Since the release 2.0.75 we intoduced a new component as I might have shared earlier, the Decision Maker, to handle the management of the status decision in a more robust and much more effiscient way.
Since this version, we also made a couple of adjustments and fixes.

The last vetted version for Cloud is 2.0.82, could you request the upgrade please?

Also, in the meantime, please share the status_message_json value, you can see it in the "status message" tab of a given entity that is red and shouldn't be based on the logical group membership.

You can also get it by calling the macro:

```
| `get_splk_dhm_table(mytenant, compact, *, *)`
```

In the decision maker, we handle the logical group and context information:

```
    """
    Create a function called get_logical_group_status:
    - arguments: object_group_key, object_group_name, object_group_min_green_percent, object_group_green_percent
    - behaviour: returns booleans: isUnderLogicalGroup, LogicalGroupStateInAlert 
      isUnderLogicalGroup: True if object_group_key is defined
      LogicalGroupStateInAlert: True if object_group_key is defined and object_group_min_green_percent is lower than object_group_green_percent, False otherwise
    """

    def get_logical_group_status(
        self,
        object_group_key,
        object_group_name,
        object_group_min_green_percent,
        object_group_green_percent,
        object_group_members_count,
        object_group_members_red,
    ):
        if object_group_key != "":
            isUnderLogicalGroup = True
            if object_group_min_green_percent < object_group_green_percent:
                LogicalGroupStateInAlert = True
                LogicalGroupMsg = f"""Logical Group {object_group_name} with key="{object_group_key}" is in alert state. The minimum green percent is {object_group_min_green_percent} which is lower than the minimal green percent of {object_group_green_percent}, object_group_members_count={object_group_members_count}, object_group_members_red={object_group_members_red}"""

            else:
                LogicalGroupStateInAlert = False
                LogicalGroupMsg = f"""Logical Group {object_group_name} with key="{object_group_key}" is in normal state. The minimum green percent is {object_group_min_green_percent} which is higher or equal to the minimal green percent of {object_group_green_percent}, object_group_members_count={object_group_members_count}, object_group_members_red={object_group_members_red}"""

        else:
            isUnderLogicalGroup = False
            LogicalGroupStateInAlert = False
            LogicalGroupMsg = ""

        return isUnderLogicalGroup, LogicalGroupStateInAlert, LogicalGroupMsg
```

We then call this function as:

```
                    # call get_logical_group_status and define isUnderLogicalGroup and LogicalGroupStateInAlert
                    (
                        isUnderLogicalGroup,
                        LogicalGroupStateInAlert,
                        LogicalGroupMsg,
                    ) = self.get_logical_group_status(
                        object_group_key,
                        object_group_name,
                        object_group_min_green_percent,
                        object_group_green_percent,
                        object_group_members_count,
                        object_group_members_red,
                    )
                    logging.debug(
                        f'tenant_id="{self.tenant_id}", object_value="{object_value}", key_value="{key_value}", isUnderLogicalGroup="{isUnderLogicalGroup}", LogicalGroupStateInAlert="{LogicalGroupStateInAlert}", LogicalGroupMsg="{LogicalGroupMsg}", object_group_key="{object_group_key}", object_group_name="{object_group_name}", object_group_min_green_percent="{object_group_min_green_percent}", object_group_green_percent="{object_group_green_percent}", object_group_members_count="{object_group_members_count}", object_group_members_red="{object_group_members_red}"'
                    )
```

If you:

- Enable debug mode in Configuration
- Loads the tenant, or call the macro in SPL as previously mentioned
- Then look into the following log with the key word search:

```
index=_internal sourcetype="trackme:custom_commands:trackmedecisionmaker" "isUnderLogicalGroup="
```

And can share this, we will get the full context.

There might be something I am not seeing specific to your configuration / context but this would tell us what we need to know.

Thank you

**Comment by bdcrandall** [comment]
Here's the first thing you wanted, the status message:
![trackmev2_bug05](https://github.com/trackme-limited/trackme-report-issues/assets/66020496/19f58223-c477-4a8b-9d55-821d0526a8f5)

**Comment by guilhemmarchand** [comment]
@bdcrandall 

Ok so that's telling us the things, I believe we have located the root cause and indeed it should be blue, we will follow up shortly

**Comment by guilhemmarchand** [comment]
Hi @bdcrandall 

TrackMe Version 2.0.83 was published today, and is now pending for Splunk Coud vetting.
Release notes:

https://docs.trackme-solutions.com/latest/releasenotes.html

We believe all issues related to Logical Groups have been addressed witrh a deep rewrite of the backend side management of Logical Groups, there has been also important fixes, improvements and also a new UI that makes management and review easier.

Please confirm back in this issue when you have the chance to validate then we can close it.
We will keep it opened for now until we get some news from you.

Thank you!

**Comment by bdcrandall** [comment]
Apologies for the delay in following up.  I am confirming that 2.0.83 fixed this bug.

**Comment by guilhemmarchand** [comment]
Thank you @bdcrandall !
