### ISSUE TITLE
Feature - Configurable min & max delay values for adaptive thresholding

### ISSUE THREAD

**Issue by sebwurl** [trackme-limited/trackme-report-issues#473]
It looks like the adaptive thresholding uses a min_value of 3600s and a max_value of  604800s. It would be great to have an option to adjust these values globally per tenant.

**Comment by guilhemmarchand** [comment]
Hi @sebwurl !

These options are parts of the command line arguments of the scheduled which is created with the tenant / component, for instance:

```
| trackmesplkadaptivedelay tenant_id="01-feeds" component="dsm" min_delay_sec=3600 min_historical_metrics_days=7 earliest_time_mstats="-30d" max_runtime=900 max_auto_delay_sec=604800 max_changes_past_7days=10
```

<img width="1728" alt="image" src="https://github.com/trackme-limited/trackme-report-issues/assets/7503059/c6dfe87f-8d2e-4867-9dea-6a1bd6e8df5a">


with:

- min_delay_sec=3600
- max_auto_delay_sec=604800

So one can update these values per tenant / component for adjustment purposes, does that fullfil your request?

**Comment by sebwurl** [comment]
Awesome, thanks. These changes will not have any negative effect on upcoming app upgrades right?

**Comment by guilhemmarchand** [comment]
Hi @sebwurl 
No, you totally can fine tune these settings, it is not planned to change this in a future release.

Guilhem

**Comment by guilhemmarchand** [comment]
Assuming I answered your questions @sebwurl let me know otherwise ;-)
