### ISSUE TITLE
bug - Virtual Tenant UI - overview duplicates entities in red state

### ISSUE THREAD

**Issue by sebwurl** [trackme-limited/trackme-report-issues#486]
On the landing page for the created virtual tenants, the KPI for red status entities is wrong (at least for low priority entities).
![image](https://github.com/trackme-limited/trackme-report-issues/assets/85566586/c7588ac6-d863-4e9a-a4fe-548e99f2d091)
![image](https://github.com/trackme-limited/trackme-report-issues/assets/85566586/f3efa37d-5495-4911-8b2d-bc224b49ae1f)

Every time I looked at it, the actual amount of entities was doubled in the overview page.
This happens in v2.0.78 SplunkCloud and v2.0.81 OnPrem

**Comment by sebwurl** [comment]
Hi,
using your provided search, the fields 
- dsm_entities
- dsm_low_red_priority
- dsm_medium_red_priority
- dsm_high_red_priority

show correct results.

**Comment by guilhemmarchand** [comment]
Thank you very much @sebwurl
