### ISSUE TITLE
feature request - Filter option for acknowledged entities

### ISSUE THREAD

**Issue by sebwurl** [trackme-limited/trackme-report-issues#493]
In earlier versions it was possible to filter for acknowledged entities directly in the column header.
![image](https://github.com/trackme-limited/trackme-report-issues/assets/85566586/68b793fb-c2c1-4d95-82af-44d4a06ee102)

It would be great to have this option again. Or even better, to have it available within the "filter field or function" dropdown.
![image](https://github.com/trackme-limited/trackme-report-issues/assets/85566586/bc9c5337-7fd2-43ad-abf9-653f53d17934)

**Comment by guilhemmarchand** [comment]
Great suggestion thanks, added at the bottom of the dropdown: (for all components)

![CleanShot 2024-02-13 at 00 57 59@2x](https://github.com/trackme-limited/trackme-report-issues/assets/7503059/ce6c8699-f86f-4672-92e3-5a75ddbcf170)
