### ISSUE TITLE
enhancement - Adaptive Threshold for Feeds tracking (splk-dsm/splk-dhm) - Use max_auto_delay_sec in case the calculated threshold is higher than max_auto_delay_sec 

### ISSUE THREAD

**Issue by sebwurl** [trackme-limited/trackme-report-issues#495]
TrackMe v2.0.83

For various entities I'm seeing internal TrackMe events like:

`2024-02-12 16:00:33,708 INFO trackmesplkadaptivedelay.py .... refusing to update the lag policy as it is bigger than the max_auto_delay_sec=604800`

I would still expect a change to be made: an adjustment to the max_auto_delay_sec. Instead the adaptive delay tracker does not touch this entity.

**Comment by guilhemmarchand** [comment]
Hi @sebwurl 

So the option "max_auto_delay_sec" is an argumnent part of the adaptive tracker which is meant to prevent the Outliers calclucation from generating situations where TrackMe says it's ok not to have data for many weeks or more for a given entity, without further human control, one can update this value to accept bigger values if the context implies many entities that have that type of frequency.

Would you suggest that we should have a further logic handling these types of use cases right?

**Comment by sebwurl** [comment]
I'll try to clarify my point.
Let's say the entity has a configured delay of 6d. When the adaptive delay calculates a new threshold of 8d, it looks like the entity is not changed and still has a configured delay of 6d. I thought it should be set to 7d (max_auto_delay_sec) in this scenario.

So at some point I would expect all "missing" entity to have a configured threshold that is equal to max_auto_delay_sec. 
Currently I'm experiencing entities like this:
![image](https://github.com/trackme-limited/trackme-report-issues/assets/85566586/ffda5764-9502-4699-b6dc-60c4c13b42e7)

**Comment by guilhemmarchand** [comment]
I see your point ;-)

Basically saying, if TrackMe's calculation end up going over the limit, then we should apply that limit instead of not doing anything right.

That's not lacking sense - thinking about it

**Comment by guilhemmarchand** [comment]
Approach validated @sebwurl 
From 2.0.84, TrackMe will use the max allowed value if the calculation goes beyond it, then once updated the entity enter the cycle of review transparently.

Thanks for sharing your thoughts and making TrackMe always better ;-)
