### ISSUE TITLE
bug - Tenants Knowledge Objects permissions issue with Schema Upgrade - Read and Write permissions were inverted in the Schema upgrade in recent versions using standardized libs to manipulate KOs, this leads created objects during the schema upgrade to eventually define inconsistent permissions. This update fixes it and also automatically fixes any existing tenant

### ISSUE THREAD

**Issue by guilhemmarchand** [trackme-limited/trackme-report-issues#497]
**bug - Tenants Knowledge Objects permissions issue with Schema Upgrade - Read and Write permissions were inverted in the Schema upgrade in recent versions using standardized libs to manipulate KOs, this leads created objects during the schema upgrade to eventually define inconsistent permissions. This update fixes it and also automatically fixes any existing tenant**

**Comment by Tinman51** [comment]
Is there a script or command we can run to fix while this release is prepped etc?

**Comment by Tinman51** [comment]
Could this be a cause after upgrading from 71 to 83 that our DSM home page isn't showing any data from the KV Store KV lookup?

**Comment by guilhemmarchand** [comment]
Right this cannot hurt to do so as what TrackMe will do is applying the permissions as these should according to the tenant configuration, so I would advise you go with that.

However, your issue may be somewhere else, I would think permission and capabilities related.

You can try:

Run this: (change the tenant)

```
| `get_splk_dsm_table(mytenant, *)`
```

And see if you get results and/or any errors

Also please run:

```
| trackmeload
```

And see what comes from it.

Also make you are compliying with capabilities requirements:

https://docs.trackme-solutions.com/latest/admin_guide_rbac.html

If TrackMe is encountering something unexpected, this will be logged:

https://docs.trackme-solutions.com/latest/troubleshoot.html

**Comment by Tinman51** [comment]
get table call gave an error: "Error at.../search_command.py", line 959:line contains NUL

**Comment by guilhemmarchand** [comment]
Can you checkout the logs from the trackmedecisionmaker?

```
index=_internal sourcetype=trackme:custom_commands:trackmedecisionmaker
```

We need to isolate where the issue stands, you seem to have something unexpected here.

Let's try this:

```
| inputlookup trackme_dsm_tenant_$tenant_id$ where _key="mytenant"
| eval keyid=_key
| `trackme_default_priority`
```Retrieve ML anomaly detection status```
| `get_splk_outliers_status($tenant_id$, "dsm")`
| `trackme_splk_dsm_group_lookup($tenant_id$)`
| trackmedecisionmaker tenant_id="mytenant" component="dsm" 
```

If fails, remove the decision maker line and re-run

**Comment by Tinman51** [comment]
what value should "mytenant" be? Is it the same as $tenant_id$?

**Comment by guilhemmarchand** [comment]
In the searches above $tenant_id$ and mytenant should be replaced the actual value of your tenant

**Comment by Tinman51** [comment]
I put wildcard in and got the error in decisionmaker, once I removed the decisionmaker line, it returns fine

**Comment by guilhemmarchand** [comment]
Can you drop me an email at gmarchand@trackme-solutions.com?
We can have a zoom in 30min from now if you like

**Comment by Tinman51** [comment]
unfortunately I cant screen share without contractual documentation and NDA etc in place.

**Comment by guilhemmarchand** [comment]
@Tinman51 

No, you can't put a wildcard here.

Say my tenant is "01-feeds", the search is:

```
| inputlookup trackme_dsm_tenant_01-feeds
| eval keyid=_key
| `trackme_default_priority`
```Retrieve ML anomaly detection status```
| `get_splk_outliers_status(01-feeds, "dsm")`
| `trackme_splk_dsm_group_lookup(01-feeds)`
| trackmedecisionmaker tenant_id="01-feeds" component="dsm"
```

Once you run this and if it fails, checkout the decisionmaker logs, there must be some inconsistency which leads to this and we will see traces in the logs:

index=_internal sourcetype=trackme:custom_commands:trackmedecisionmaker log_level=error

**Comment by guilhemmarchand** [comment]
Ok it's a bit difficult to say like that, however:

- Does the exception is raised by Splunk directly? (like for instance when you do a syntax error ) if so, open the inspector log of the search that Splunk provides and read the exception, there will be more indications

- Also read carefully the logs from the decision maker, if it's a Python exception there will be more than just this error.

End of the day, there must be some wrong records for some reasons, one option to fix the situation would be to clear up the Kvstore, let TrackMe re-discover things then re-apply things like priority and so forth.

You would just just a backup of the collection to a CSV (inputlookup then outputlookup), and to clear the KV you just need to do:

```
| outputlookup trackme_dsm_tenant_<name of the tenant)
```

Of course this is a bit radical, but we can always re-apply configuration from the backup - unless we find out the reaons why it fails.

**Comment by Tinman51** [comment]
1) I looked in the inspector and found a couple of additional errors:
   a. ERROR SearchPhaseGenerator - Failed to create the AST for search
   b. ERROR SearchOperator:filter - error ins 'where' command: The expression is malformed. An unexpected character is reached at '[ |inputlookup trackme_datagenredacted where (component=dsm AND regex=true AND target=allowlist AND addprefix=true and fields=index) | append [ makeresults...

2) The only error messages in internal are the same line 959 ones (contains NUL)

I am still hoping to not have to restore the KV but will keep trying to replicate the error. What files does the 'trackmedecisionmaker' access so I can check permissions on those as well?

**Comment by guilhemmarchand** [comment]
@Tinman51 

I think you have found the issue:

```
b. ERROR SearchOperator:filter - error ins 'where' command: The expression is malformed. An unexpected character is reached at '[ |inputlookup trackme_datagenredacted where (component=dsm AND regex=true AND target=allowlist AND addprefix=true and fields=index) | append [ makeresults...
```

it sounds like something is not consistent in the allow list, I would advise you to purge this Kvstore:

```
| outputlookup trackme_common_datagen_cache_tenant_<name of the tenant>
```

Then try to re-load the tenant, this Kvstore will be re-generated automatically and is updated when you define constrains in the dataset (the button Manage: Dataset access)

Most likely, an invalid regex was entered at some point

**Comment by Tinman51** [comment]
The issue still occurs when we dont reference ANY datagen data as well. Unless the decisionmaker does somewhere?

This search returns the same line959 error but nothing in the search.log
`| inputlookup trackme_dsm_tenant_$tenant_id$ where _key="mytenant"
| eval keyid=_key
| `trackme_default_priority`
```Retrieve ML anomaly detection status```
| `get_splk_outliers_status($tenant_id$, "dsm")`
| `trackme_splk_dsm_group_lookup($tenant_id$)`
| trackmedecisionmaker tenant_id="mytenant" component="dsm" `

**Comment by guilhemmarchand** [comment]
Can you please share the exact search you are running and the name of your tenant.

The search you are are showing has mix of "mytenant" and "$tenant_id$" both are meant to replaced

**Comment by Tinman51** [comment]
Here is the error when running just the trackmedecisionmaker

**Comment by Tinman51** [comment]
here is the redacted search (redacted=my tenant name)
| inputlookup trackme_dsm_tenant_redacted where _key="*"
| eval keyid=_key
| `trackme_default_priority`
```Retrieve ML anomaly detection status```
| `get_splk_outliers_status(redacted, "dsm")`
| `trackme_splk_dsm_group_lookup(redacted)`
| trackmedecisionmaker tenant_id="redacted" component="dsm"

**Comment by guilhemmarchand** [comment]
Thank you, let me review that and give you more troubleshooting steps.

In the meantime, what about creating another tenant for the testing purposes with a tracker looking at a few indexes? This would validate that the issue is located on this tenant only

**Comment by guilhemmarchand** [comment]
@Tinman51 

Can we please continue this discussion by email? (support@trackme-solutions.com)

We will need to have some confirmation:

- The Splunk version and type of Splunk deployment (Splunk Enterprise / Splunk Cloud)
- Are you running in FIPS mode or Gov Cloud?

Definitvely, the following search should just work:

```
| inputlookup trackme_dsm_tenant_01-feeds
| eval keyid=_key
| `trackme_default_priority`
```Retrieve ML anomaly detection status```
| `get_splk_outliers_status(01-feeds, "dsm")`
| `trackme_splk_dsm_group_lookup(01-feeds)`
| trackmedecisionmaker tenant_id="01-feeds" component="dsm"
```

**What does the command trackmedecisionmaker do?**

This is a Python custom command, a streaming custom command, which handle decisions for TrackMe, it takes upstream the KVstore record, investigates the different record information, correlates and defines the entities status.

It does not especially do exotique things compared to all backends in TrackMe, it doesn't itself performs searches but handles manages the information from records.

We would advise you to create a brand new virgin TrackMe tenant to verify if this issue is somehow linked to the existing tenant (if you have reached the current number of free tenants, we can grant you a temporary license.

In this new tenant, we would want to verify that the decision maker command can run with no issues or not, this would a very easy way to understand the issue.

**Comment by Tinman51** [comment]
I will reach out via email, but as an update I created a test tenant from scratch, with a single DSM record and we didnt get the error. so it must be data driven?

**Comment by Tinman51** [comment]
This was resolved in the DSM KV store lookup. It was unprintable character in a sourcetype that came in via the automated process.

I will fill out an enhancement request to put a check in for unprintable characters when creating new sourcetypes in the lookup.
