### ISSUE TITLE
feature - Filter for acknowledgement comment content in main dashboard

### ISSUE THREAD

**Issue by sebwurl** [trackme-limited/trackme-report-issues#505]
It would be great to have the option to filter for specific content in the ack comments via the existing dropdown menu in the main dashboard. For example this would enable the user to filter for the automatically created ack (-comments), that need a first evaluation. Next to that users could reference "task owners" (by just typing a colleagues name or splunk account) within the ack comment, when setting custom acks.

**Comment by guilhemmarchand** [comment]
![CleanShot 2024-03-30 at 12 50 55@2x](https://github.com/trackme-limited/trackme-report-issues/assets/7503059/d7ecb59f-9a53-4f79-a198-4e9d6404a9b0)

**Comment by guilhemmarchand** [comment]
Added for Version 2.0.87 @sebwurl
