### ISSUE TITLE
TrackMe bug report - entities turned red and alerted without latency or delay thresholds being exceeded

### ISSUE THREAD

**Issue by bdcrandall** [trackme-limited/trackme-report-issues#507]
**Describe the bug**
This happened for two entities for me this morning.  Alerts fired and status message showed red even though latency and delay were both well within specification.

**TrackMe version**
2.0.83

**To Reproduce**
I'm not quite sure, it only happened for two of my many entities.

**Expected behavior**
The entity should remain green.

**Screenshots**
Here's the text from the alert:

Email timestamp: Thu 2/22/2024 9:21 AM

Feed priority is high
Alert reason is lag_threshold_breached

Monitoring conditions are not met due to latency issues. Ingestion latency is approximately 5980.664 seconds (duration: 01:39:40), which is higher than the maximum allowed latency of 3600.0 seconds (duration: 01:00:00), latest event available (_time) for this entity: 22 Feb 2024 09:19, latest event indexed (_indextime) for this entity: 22 Feb 2024 09:17

**Splunk version and deployment:**
Splunk Cloud
Version: 9.0.2303.201
Build: 5480631d4591
Experience: Classic
Standalone search head

**Additional context**
Both entities were in index=unix with Priority=high.  Neither was in a logical group.

**Comment by guilhemmarchand** [comment]
Hi @bdcrandall 

This unlikley a bug and unlikely not to be justified.

The most probable reason is that you have had a bunch of events that came very late compared to their original creation on the endpoints, which polluted / impacted the latency calculation temporarily.

If you have an alert which triggered and you have left enabled the Smart Status action, look into this:

```
index=trackme_summary sourcetype="trackme:smart_status" "lag_threshold_breached"
```

Especially, you will see very interesting things like:

![CleanShot 2024-02-22 at 17 03 30@2x](https://github.com/trackme-limited/trackme-report-issues/assets/7503059/8ca1f172-584f-4d07-b59b-aead84ad87d3)

**Comment by sebwurl** [comment]
@bdcrandall Is your assumption based on the entities "Overview data source" chart, where you do not see the avg breaching your thresholds? If this is the case, select a smaller timerange for the chart or open the underlying search in a separate search window, then select an appropriate timerange and adjust the span to 5m in the final timechart. 
In the dashboard panel, the span for the underlying timechart is depending on the selected timerange (longer timerange, higher span). Maybe you looked at a chart where the avg was build on time bins of 1h and these avgs were not breaching thresholds, but breaking it down to 5m bins might show the breach.
