### ISSUE TITLE
bug - Data Source tracking (splk-dsm) - Allow Adaptive Delay field persistence is not honoured by hybrid trackers

### ISSUE THREAD

**Issue by sebwurl** [trackme-limited/trackme-report-issues#539]
In v.2.0.84 I'm trying to make a bulk disablement for the adaptive delay.
I'm running this search, to load needed object names and pass it to the rest endpoint.

```
| inputlookup trackme_dsm_tenant_my_tenant
| search object="<my_search_criteria>" AND allow_adaptive_delay=true

| stats values(object) as object
| eval object=mvjoin(object,",")

| map search="| trackme url=\"/services/trackme/v2/splk_dsm/write/ds_update_lag_policy\" mode=\"post\" body=\"{'tenant_id': 'my_tenant','object_list': '$object$','data_max_lag_allowed':'3600','data_max_delay_allowed':'3600','data_lag_alert_kpis':'all_kpis','allow_adaptive_delay':'false'}\""
```

This works fine so far. The result only shows success messages. And I can run a search to verify that allow_adaptive_delay=false is set for all my selected entities:

```
| inputlookup trackme_dsm_tenant_my_tenant
|  search object="<my_search_criteria>"
| stats count by allow_adaptive_delay 
```

Running the same search after a short time, it shows that some entities are reset allow_adaptive_delay=true and the adaptive delay tracker is doing adjustments. Is there any reason why this should happen?

**Comment by sebwurl** [comment]
After a while, all entities that were adjusted via the endpoint are reset to allow_adaptive_delay=true

**Comment by guilhemmarchand** [comment]
Thank you @sebwurl - Will review ASAP

**Comment by guilhemmarchand** [comment]
So the issue stands in a macro:

```
# splk-dsm persistent fields lookup call
[trackme_dsm_lookup_persistent_fields(1)]
args = tenant_id
definition = lookup local=t trackme_dsm_tenant_$tenant_id$ object OUTPUT _key as key, priority, alias, data_max_lag_allowed, data_max_delay_allowed, future_tolerance, data_lag_alert_kpis, monitored_state, data_monitoring_wdays, data_monitoring_hours_ranges, data_override_lagging_class, min_dcount_host, min_dcount_field, min_dcount_threshold, tags_manual, latest_flip_time, latest_flip_state, object_state, tracker_runtime, data_first_time_seen, outliers_readiness
iseval = 0
```

This macro is called by the trackers, it needs to contain the list of fields which are persistent over iterations, as you can see it's missing the allow_adaptive_delay. (not the very first time I get the same issue - need to think about it!)

So we need to have the field added to the list, then all trackers (hybrid and others will make this information persistent), if you need to address this immediately, you can customize the macro, then once you have the release of TrackMe fixing it, make sure to get this cleared from the local to avoid issues in the future.

**Comment by guilhemmarchand** [comment]
Added for TrackMe 2.0.87.

**Comment by sebwurl** [comment]
In this case I will just wait for the update.

Because one of the conditions mentioned in the docs is data_override_lagging_class!=true, I thought this parameter could be used as workaround without changing the macro (data_override_lagging_class is already included)
![image](https://github.com/trackme-limited/trackme-report-issues/assets/85566586/abf1d15c-8524-4c41-91a9-4e68c4cbf803)

So I expected, that entities will not be changed when data_override_lagging_class=true no matter what is defined for allow_adaptive_delay. But this did not work, the adaptive delay tracker still makes adjustments. Is this intended?

**Comment by guilhemmarchand** [comment]
So, at the Python level, these are the conditions for the entity to be considered:

```
                    if (
                        item.get("monitored_state") == "enabled"
                        and item.get("object_state") == "red"
                        and "delay_threshold_breached" in anomaly_reason
                        and current_delay > float(min_delay_sec)
                        and data_override_lagging_class != "true"
                        and allow_adaptive_delay == "true"
                    ):
                        collection_records.append(item)
                        collection_records_dict[item.get("_key")] = {
                            "object": item.get("object"),
                            "current_max_lag_event_sec": item.get(
                                "data_max_delay_allowed"
                            ),
                        }
                        count_to_process_list.append(item.get("object"))
```

If have tried this on our side and cannot seem to see not working as expected - might have been some coincidental circumstances

**Comment by guilhemmarchand** [comment]
@sebwurl 

TrackMe 2.0.87 is now live.
