### ISSUE TITLE
feature - New immutable KVstore field called ctime in TrackMe main KVstore component collections to keep track of entities origin creation time

### ISSUE THREAD

**Issue by sebwurl** [trackme-limited/trackme-report-issues#565]
It would be great to have an indicator, when a DSM entity was initially created by tracker.

My idea is a persistent epochtime value in the KVStore  _trackme_dsm_tenant_<my_tenant>_. There is the field data_first_time_seen, but this can be biased by late arriving data, as it is based on the event _time of the data source (especially when the trackers have a wider timerange). For example the tracker could use something like _entity_creation_time=now()_. So this would be the timestamp when the entity is initially added to the KVStore and it will never change, unless the entity is deleted and re-created.

This timestamp could help in various custom background operations, for example scheduled rest api operations. Maybe it could also be an interesting KPI, when it is translated to a human readable age of an entity that is a column in the main dashboard (to easily identify new entities that might require some initial tuning / review.)

**Comment by guilhemmarchand** [comment]
Thank you for the feature request @sebwurl and I agree, it fully makes sense.

From version 2.0.89, a new field will be added to the KVstore collections, called "ctime", this is an immutable field (unless manually changed) which contains the original creation timestamp in epochtime when entities have been added to the collection.

If you wished to backfil some specific collections to initialse the ctime to the closer value using the first time seen field, this could be done in a few lines of SPL, if so let me know and I can share a search if needed.

Thank you!

Guilhem

**Comment by sebwurl** [comment]
Awesome, thank you.
