### ISSUE TITLE
bug - New ctime field is not persistent in some components (dsm, wlk)

### ISSUE THREAD

**Issue by sebwurl** [trackme-limited/trackme-report-issues#584]
The new field "ctime" introduced in version 2.0.89 is not persistent (for dsm). The ctime value is updated with every run of the tracker. Most likely this is caused by a missing adjustment in  the corresponding macro **trackme_dsm_lookup_persistent_fields(1)**

**Comment by guilhemmarchand** [comment]
Hi @sebwurl 

Ha damned... this one again!
Thanks for raising

**Comment by guilhemmarchand** [comment]
confirmed and will be fixed in the next release, my aplogises for this failure.

 in the meantime if you want to address this immediately you just need:

```
# splk-dsm persistent fields lookup call
[trackme_dsm_lookup_persistent_fields(1)]
args = tenant_id
definition = lookup local=t trackme_dsm_tenant_$tenant_id$ object OUTPUT _key as key, ctime, priority, alias, data_max_lag_allowed, data_max_delay_allowed, future_tolerance, data_lag_alert_kpis, monitored_state, data_monitoring_wdays, data_monitoring_hours_ranges, data_override_lagging_class, min_dcount_host, min_dcount_field, min_dcount_threshold, tags_manual, latest_flip_time, latest_flip_state, object_state, tracker_runtime, data_first_time_seen, outliers_readiness, allow_adaptive_delay
iseval = 0
```
