### ISSUE TITLE
Feature request - Collapse & decollapse the DSM main table

### ISSUE THREAD

**Issue by sebwurl** [trackme-limited/trackme-report-issues#704]
It would be very comfortable to have an option to collapse & decollapse all DSM main table entries with one click.
![image](https://github.com/user-attachments/assets/a370cd76-8821-4648-9e4a-804fd85b38f6)

If possible, the current view (custom collapsing) should not be reset by the table refresh.

**Comment by guilhemmarchand** [comment]
Thank you @sebwurl - will check for this ;-)

**Comment by guilhemmarchand** [comment]
@sebwurl 

This is being reviewed, and a bit trickier than expected ;-) 

FYI, here is an associated update to your request:
https://github.com/trackme-limited/trackme-report-issues/issues/708

**Comment by guilhemmarchand** [comment]
Ready for 2.0.98 @sebwurl !

![CleanShot 2024-07-21 at 20 05 32@2x](https://github.com/user-attachments/assets/aecd24c3-5095-4615-9724-4fe2815adb5a)


In addition with some bonus features ;-)

**Comment by sebwurl** [comment]
That looks awesome :)

**Comment by guilhemmarchand** [comment]
Thank you @sebwurl ;-)
yes it's quite good actually, you can also from this release do multi-level grouping in the Tabulator, as well as use expressions to create a custom group - we'll document that

2.0.98 is on the final run to be published this week
