### ISSUE TITLE
bug - Data Source tracking (splk-dsm) - Grouping issues with reduced pagination and entities for the same indexes that are split over multiple pages

### ISSUE THREAD

**Issue by sebwurl** [trackme-limited/trackme-report-issues#737]
In v2.0.98. a reduced tabulator pagination size (on tenant level) for the DSM results in multiple groups for the same data_index on different pages.
For example for index=_internal. After opening the tenant, the page 1 shows 4 objects.
![image](https://github.com/user-attachments/assets/17b7e2d1-72eb-481a-a314-3a2494b24c6b)

Moving to page 2, _internal is still on top of the table with some more objects:
![image](https://github.com/user-attachments/assets/f3c564dc-a657-4ac4-b371-8d1f2901a4db)

Moving to page 3, _internal ist still on top with some objects. And so on.

**Comment by guilhemmarchand** [comment]
Thank you @sebwurl 
Evaluating this!

**Comment by guilhemmarchand** [comment]
@sebwurl 

So, this is interesting, the behaviour I am seeing looking at is basically that if a given index has more entities than the reduced pagination size, it gets split into two pages:

![CleanShot 2024-08-11 at 12 42 14@2x](https://github.com/user-attachments/assets/ca1940dc-1d1d-48e1-a33e-699e8c3daa01)

![CleanShot 2024-08-11 at 12 42 30@2x](https://github.com/user-attachments/assets/0a8ea236-6d06-430b-a81b-67e9830289ee)

However, I believe we can avoid this situation you are describing at the level of the Tabulator:

```
        groupBy: isExpression
          ? function (data) {
              return tabulatorGroupBy(groupByContext, data);
            }
          : convertCsvToArray(groupByContext),
        initialSort: [
          //set the initial sort order of the data
          { column: "object", dir: "asc" },
        ],
```

In the initialSort, we should also add the index field - reviewing this.
