### ISSUE TITLE
feature - Data Sources/Data Hosts tracking (splk-dsm/splk-dhm) - Add avg/max choices and additional choices with treshold in performance metrics tab

### ISSUE THREAD

**Issue by sebwurl** [trackme-limited/trackme-report-issues#751]
Looking at the data sources details panels, we can see avg,latest,perc and stdev values. This can be a bit confusing when reviewing alerts.
Often when I review the alerted data source, I don't see the breach from the panels, because of these functions and the dynamic time span. Then I drilldown into the searches and adjust the calculations to max values, because they are responsible for a fired alert. Having max values in the default panels would be very helpful.

**Comment by guilhemmarchand** [comment]
Hi @sebwurl !

Thank you for your sharing your feedback and thoughts, this is extremely valuable.

![CleanShot 2024-08-14 at 10 20 15@2x](https://github.com/user-attachments/assets/dfca484b-672f-46fe-91dc-e640e1890878)

Let me know your thoughts

Guilhem

**Comment by sebwurl** [comment]
I don't think the single value at the top is necessary. For me, the most interesting thing is to view it over time.
For the panel it might be better to have an option to chart max instead, for better readability? But both ways would be fine for me. Having the max in the performance metric tab would be great as well.

Having these topics in mind: Would it be possible to plot the defined thresholds as overlay in the panels as well? This would be a good visual indicator of how close the entity is to the threshold values.

**Comment by guilhemmarchand** [comment]
Understood thanks @sebwurl 
Checking if it can be integrated for 2.0.99

**Comment by guilhemmarchand** [comment]
@sebwurl 

The following will be made available in 2.0.99, all changes are regarding the performance metrics tab only at this stage. (I might review the overview screen but it's more tricky here)

In short, I've added several selections, with avg/max at the timechart level as well as the treshold in overlay. (the treshold is made available in oberlay for delay too)

A few screenshots:

![CleanShot 2024-08-14 at 16 36 39@2x](https://github.com/user-attachments/assets/0969045a-dc44-4090-9c74-115c9b34186e)

![CleanShot 2024-08-14 at 16 37 10@2x](https://github.com/user-attachments/assets/3fb719c4-96ed-4010-b3e7-3df1fbf76746)

**Comment by sebwurl** [comment]
Awesome. having it in the performance metrics tab is totally fine.
