### ISSUE TITLE
bug - TrackMe Hybrid trackers - In some unexpected circumstances, an Hybrid tracker and its references may be missing from the central collection. While the Hybrid tracker exists, TrackMe's run tracker dropdown will not provide the tracker as executable

### ISSUE THREAD

**Issue by sebwurl** [trackme-limited/trackme-report-issues#777]
I'm on v2.1.0.
When navigation to _DSM -> Run Tracker Reports_ in the Main Dashboard, the dropdown only provides one tracker although two are configured.

**Comment by guilhemmarchand** [comment]
This sounds like an issue in the main collection, the search populating it is driven by:

```
| inputlookup trackme_virtual_tenants where tenant_id="$tenant_id$" | table tenant_dsm_hybrid_objects | spath input=tenant_dsm_hybrid_objects | rename "reports{}" as reports | fields reports | mvexpand reports | where match(reports, "_tracker_tenant_")
```

Hybrid trackers themselves are stored in the following KV:

```
| inputlookup trackme_dsm_hybrid_trackers_tenant_mytenant
```

I am guessing the main collection lacks the proper hybrid tracker?

**Comment by sebwurl** [comment]
`| inputlookup trackme_dsm_hybrid_trackers_tenant_mytenant`
This lookup includes both trackers.

Them main collection only includes one of it.
Tracker setup was done with the TrackMe Workflow. Not manipulation afterwards.

**Comment by guilhemmarchand** [comment]
Fine thanks @sebwurl I am guessing something went wrong at some points, for some reasons it sounds like the KVrecord was not created / made persistent. (will tripple check!)

Can you please share both contents, either here or by email (nothing in this sensitive) then I will give you clear instructions to fix it.

**Comment by guilhemmarchand** [comment]
**bug - TrackMe Hybrid trackers - If some unexpected reasons, an Hybrid tracker and its references are missing from the central collection, while the Hybrid tracker exists, TrackMe's run tracker dropdown will not provide the tracker as executable**

- To handle this potential issue, while unexpected, a new task named "check_trackers_definition" has been implemented in the Virtual Tenant health tracker.
- This task ensures that the central KV collection hybrid field for the component is consistent according to the hybrid tracker KV collection, and will fix the record automatically if necessary

![img-000076@2x](https://github.com/user-attachments/assets/7dc2cdfe-6d95-4f13-97d8-0e56ef7cb5e7)

**Comment by sebwurl** [comment]
I don’t see any major impact at the moment, so I think I can just wait for the next release that will fix it automatically?

**Comment by guilhemmarchand** [comment]
> I don’t see any major impact at the moment, so I think I can just wait for the next release that will fix it automatically?

@sebwurl Yes that is correct, zero impact except not being to manually execute the tracker from the UI ;-)
