### ISSUE TITLE
TrackMe bug report - Javascript TypeError when opening Virtual Tenant dashboard

### ISSUE THREAD

**Issue by Eolo-paolomarazzi** [trackme-limited/trackme-report-issues#864]
**Describe the bug**
I created a new new `Virtual Tenant` following the [Quick Start Guide](https://docs.trackme-solutions.com/latest/white_paper_starting_with_trackme.html).
When I try to open the `Virtual Tenant` page i get the following error (screenshots in the dedicated section):

```
Couldn't parse "<div id="cssloader" class="loader loader-default is-active" data-text="Please wait while loading TrackMe components..."/> <div id="linkChoices"/> <!-- modals --> <!-- data_sources --> ...

...

... Close</button> </div> </div> </div> </div>": TypeError: can't convert null to object 
```

**TrackMe version**
Free limited edition - Version: 2.1.6

**To Reproduce**

1. Create a new `Virtual Tenant` following the [Quick Start Guide](https://docs.trackme-solutions.com/latest/white_paper_starting_with_trackme.html)
2. Open the `Virtual Tenant`

**Expected behavior**
The `Virtual Tenant` page should be loaded without any error

**Screenshots**
![image](https://github.com/user-attachments/assets/86b27aa5-655d-46d5-8ca7-35b3ffad1c84)
![image](https://github.com/user-attachments/assets/51defb21-fbde-4890-825f-fbd936affc8b)

**Splunk version and deployment:**

- Splunk core version 9.1.0.1
- I tried to install `TrackMe` on a dedicated `Search Head` and on the `Monitoring Console`. In both cases I encountered the error described above.

**Additional context**
I'm running an On-Prem distributed `Splunk Enterprise` which is composed by the following instances:
- 2 independent `Search Heads` (not clustered). One `Search Head` is also the `License Manager`
- 1 `Cluster Master` + `Monitoring Console`
- cluster of 3 `Indexers`
- 1 `Heavy Forwarder` + `Deployment Server`

**Comment by guilhemmarchand** [comment]
Hi @Eolo-paolomarazzi !
Thank you for your interest in TrackMe, let me have a look at this.

There are two options, or it is something very specific in your context (Browser, Web proxy etc) that is leading to this behaviour, or it is related that version of Splunk, and something became incompatible.

I am currently reviewing the second and will let you know shortly, TrackMe including in this version is obviously perfectly behaving as it should and this is not an error directly from our end, however I have also noticed you did not restart Splunk, please start by this.

I will confirm shortly if we see any compatibility issues with 9.1.0.1 especially.

Guilhem

**Comment by Eolo-paolomarazzi** [comment]
Hi @guilhemmarchand, thank you for your help!

I'll try to check if there is something in my environment causing the problem.

**Comment by guilhemmarchand** [comment]
I am able to reproduce the issue with 9.1.0.1:

![img-000254](https://github.com/user-attachments/assets/44a183a9-6732-4060-aa79-6ff21388ce00)

Looking at if this also happening with latest of 9.1.x

**Comment by guilhemmarchand** [comment]
@Eolo-paolomarazzi 

Happy to confirm that this issue stands with this very specific version of Splunk, 9.1.0.1, I can reproduce it and I can confirm that this is NOT happening in 9.1.7 which is the latest maintenance release from 9.1:

![img-000255](https://github.com/user-attachments/assets/b8db9914-8da3-4080-984c-303d46feb080)

**Comment by Eolo-paolomarazzi** [comment]
@guilhemmarchand, thank you for confirming the issue.
Do you plan to fix it in the next release or upgrading to Splunk 9.1.7 is the recommended approach to resolve it?

**Comment by Eolo-paolomarazzi** [comment]
Hi @guilhemmarchand 

Thank you for your help. I'll work on scheduling a Splunk upgrade in the coming weeks.

Regards,
Paolo

**Comment by guilhemmarchand** [comment]
You are more than Welcome @Eolo-paolomarazzi - thank you for reporting this and don't hesitate if you have any further issues
