### ISSUE TITLE
bug - "Show burn test search" creates a persistent macro

### ISSUE THREAD

**Issue by sebwurl** [trackme-limited/trackme-report-issues#88]
Hi,
I'm testing the Performance Benchmark feature on v.2.0.19 and recognized that it creates macros without saving the tracker.

1. **Show burn test search** creates a macro which is persistent, although the tracker is not saved.
2. **Burn Benchmark** creates a macro as well, but this seems to be cleaned up after the search is done.

Such a cleanup would be desirable for 1. as well to avoid having a bunch of unused macros from Hybrid Tracker testing.

**Comment by guilhemmarchand** [comment]
Thanks for reporting @sebwurl 
Will check it out ASAP
