### ISSUE TITLE
bug - alerts creation - incorrect statement when including orange status for entities

### ISSUE THREAD

**Issue by sebwurl** [trackme-limited/trackme-report-issues#95]
Future events lead to an orange status. However the DSM entities are not taken into account in alerts created via the UI.
The editor creates a wrong where command:   | where (object_state=\"red\" OR **state=\"object_orange\"**)

Next to that, an entity with an orange state can not be acknowledged manually, the option is greyed out
![image](https://user-images.githubusercontent.com/85566586/232799024-f633cf37-e25f-4cbd-9da5-6f161929d44b.png)

**Comment by guilhemmarchand** [comment]
Thank you very much @sebwurl 
Fully agreed and will be fixed in next release

**Comment by guilhemmarchand** [comment]
Fixed in version 2.0.22.
